name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v9
      with:
        pythonVersion: "3.7"   
    - name: test
      run: |
        cd ./src; (python script.py -g all )
    - run: echo "🍏 This job's status is ${{ job.status }}."