name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  
    - name: test
      run: |
        cd ./src; (python script.py -g all )
    - run: echo "🍏 This job's status is ${{ job.status }}."